#path to data
data_path:
#dataset
dataset: amr
# use 10% of the data for evaluation
test_split: 0.1
# pipeline tasks
tasks:
    load_data:
      next:
        - preprocess_data
    preprocess_data:
      next:
        - feature_engineer_data
    feature_engineer_data:
      next:
        - train_model
    train_model:
      next:
        - evaluate_model
    evaluate_model:
      next:
        - create_report
    create_report:
      next: []