package org.cmpe295.user.entity.enums;

public enum ACTION {
    NO_ACTION,
    CAPTURE_IMAGE,
    MANUAL_METER_READING,
    CONFIRM_AUTOMATED_METER_READING,
    BILL_AMOUNT_DUE,
    LINK_UTILITY_ACCOUNT


}
