services:
  utility-management-db:
    container_name: utility-management-db
    # docker image to be used
    image: mysql:8.0.0
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    volumes:
      - utility-management-db:/var/lib/mysql
      - ./init/01.sql:/docker-entrypoint-initdb.d/init-script.sql
    expose:
      # Opens port 3306 on the container
      - '3306'
    restart: always

volumes:
  utility-management-db: